import { icon, action } from './shared.mjs';
export function routines() {
  return `<section class="section routines"><div class="container"><p class="eyebrow">DO SEU JEITO</p><h2>Internet para os diferentes<br>momentos da casa.</h2><div class="routine-grid"><article class="routine home-routine"><span class="routine-number">01</span>${icon('home')}<div><p class="eyebrow">CASA E FAMÍLIA</p><h3>Uma casa.<br>Muitas conexões.</h3><p>Para assistir, conversar e estudar, mesmo quando mais de uma pessoa está conectada.</p><a href="/planos.html" class="text-link">Encontrar meu plano ${icon('arrow')}</a></div></article><article class="routine work-routine"><span class="routine-number">02</span>${icon('work')}<div><p class="eyebrow">TRABALHO E ESTUDO</p><h3>Espaço para<br>se concentrar.</h3><p>Videochamadas, aulas e arquivos pedem uma velocidade adequada à sua rotina.</p><a href="/planos.html" class="text-link">Comparar velocidades ${icon('arrow')}</a></div></article><article class="routine game-routine"><span class="routine-number">03</span>${icon('game')}<div><p class="eyebrow">JOGOS E ENTRETENIMENTO</p><h3>Seu tempo livre.<br>Bem conectado.</h3><p>Para filmes e jogos, compare os planos. Nos jogos, usar cabo pode ajudar na estabilidade.</p><a href="/planos.html" class="text-link">Ver opções ${icon('arrow')}</a></div></article></div></div></section>`;
}
export function wifi() {
  return `<section class="section wifi-section"><div class="container wifi-layout"><div><p class="eyebrow">CADA AMBIENTE CONTA</p><h2>Entenda o alcance<br>do seu Wi-Fi.</h2><p>Paredes, distância e posição do roteador podem mudar o sinal em cada cômodo. Fale com a equipe para avaliar seu ambiente e as opções disponíveis.</p>${action('Avaliar meu Wi-Fi','wifi')}</div><div class="wifi-factors"><h3>O que influencia o sinal?</h3>${[['home','Tamanho do imóvel e paredes'],['wifi','Distância e posição do roteador'],['work','Equipamento e aparelhos conectados']].map(([i,t],n)=>`<div><span class="factor-number">0${n+1}</span>${icon(i)}<span>${t}</span></div>`).join('')}<p class="small">O alcance varia de um imóvel para outro. A equipe pode orientar você após conhecer o local.</p></div></div></section>`;
}

export function business() {
  return `<section class="business-section"><div class="container business-layout"><div class="business-icon">${icon('building')}</div><div><p class="eyebrow">PARA QUEM EMPREENDE</p><h2>Internet para a rotina<br>do seu negócio.</h2><p>Conte à equipe como sua empresa usa a conexão. A AMR avalia as opções disponíveis e oferece suporte técnico com atendimento humano para sua equipe.</p></div>${action('Falar sobre internet empresarial','business','','button outline')}</div></section>`;
}
